apiVersion: apps/v1
kind: Deployment
metadata:
  name: peta-populasi-app
  namespace: researchilham
  labels:
    app: peta-populasi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peta-populasi
  template:
    metadata:
      labels:
        app: peta-populasi
    spec:
      containers:
      - name: peta-populasi-container
        image: ilhamellya/gismine:2e51816
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "20Mi"
            cpu: "50m"
          limits:
            memory: "80Mi"
            cpu: "100m"