apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: populasiapp-ingress
  namespace: researchilham
  annotations:
    # acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
    cert-manager.io/acme-challenge-type: http01
    kubernetes.io/instance: nginx-ingress
    kubernetes.io/default-backend: nginx-ingress-ingress-nginx-controller
    ingressclass.kubernetes.io/is-default-class: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ^~ /.well-known/acme-challenge/ {
        allow all;
      }
    #   location /robots.txt {
    #     return 200 "User-agent: *\nDisallow: /\n";
    #   }
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "gis.mine.my.id"
      secretName: populasi-tls
  rules:
  - host: gis.mine.my.id
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: peta-populasi-service
            port:
              number: 80