
apiVersion: v1
kind: Service
metadata:
  name: peta-populasi-service
  namespace: researchilham
  labels:
    app: peta-populasi
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: peta-populasi